#!/bin/sh
### BEGIN INIT INFO
# Provides:          cfs-registration
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:		 0 1 6
# Short-Description: Register your Raspy to cfs board.
### END INIT INFO

PATH=/sbin:/bin:/usr/bin
SERIAL=$(cat /proc/cpuinfo | grep Serial | cut -d":" -f2 | tr -d ' ')
MAC=$(cat /sys/class/net/eth0/address)
REGISTRATION_SERVICE=https://coding-for-school-boards.herokuapp.com/register

#. /lib/init/vars.sh
#. /lib/lsb/init-functions


case "$1" in
  start|"")
	[ "$VERBOSE" = no ] || log_action_begin_msg "Registering to cfs board"
	##
	SERIAL=$RANDOM$RANDOM$RANDOM

	if [ -z "$SERIAL" ]; then
	  echo "CPU Serial not found. Using mac address"
	  SERIAL=$MAC
	fi

	#curl -s $REGISTRATION_SERVICE/$SERIAL > /dev/null
	curl -s $REGISTRATION_SERVICE/$SERIAL
	ES=$?
	##
	ECHO "out ->"
	ECHO $ES
	ECHO "!DONE!"

	[ "$VERBOSE" = no ] || log_action_end_msg $ES
	;;

  stop)
	# No-op
	;;

  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;

  status)
	do_status
	exit $?
	;;

  *)
	echo "Usage: cfs-registration [start|stop|status]" >&2
	exit 3
	;;

esac
